// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Day01$Day01 = require("../Day01/Day01.bs.js");

function getFuel(fuel) {
  if (fuel <= 0) {
    return 0;
  } else {
    return fuel + getFuel(Day01$Day01.getTotalFuel(String(fuel))) | 0;
  }
}

function main(input) {
  var moduleFuels = Day01$Day01.calculateFuel(Day01$Day01.toIntegers(Day01$Day01.splitLines(input)));
  return Day01$Day01.calTotalfuel(moduleFuels.map(getFuel));
}

var Day02 = {
  getFuel: getFuel,
  main: main
};

var file = Fs.readFileSync("./input.txt", "utf8");

console.log(main(file));

exports.Day02 = Day02;
exports.file = file;
/* file Not a pure module */
