// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function splitLines(lines) {
  return lines.split("\n");
}

function toIntegers(strings) {
  return strings.map(Caml_format.caml_int_of_string);
}

function calculateFuel(masses) {
  return masses.map((function (mass) {
                return Js_math.floor(mass / 3 | 0) - 2 | 0;
              }));
}

function calculateTotalFuel(fuels) {
  return fuels.reduce((function (a, b) {
                return a + b | 0;
              }), 0);
}

function main(param) {
  var file = Fs.readFileSync("./input.txt", "utf8");
  var strings = file.split("\n");
  return calculateTotalFuel(calculateFuel(strings.map(Caml_format.caml_int_of_string)));
}

main(/* () */0);

exports.splitLines = splitLines;
exports.toIntegers = toIntegers;
exports.calculateFuel = calculateFuel;
exports.calculateTotalFuel = calculateTotalFuel;
exports.main = main;
/*  Not a pure module */
