// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function splitLines(lines) {
  return lines.split("\n");
}

function toIntegers(strings) {
  return strings.map(Caml_format.caml_int_of_string);
}

function calculateFuel(masses) {
  return masses.map((function (mass) {
                return Js_math.floor(mass / 3 | 0) - 2 | 0;
              }));
}

function calculateTotalFuel(fuels) {
  return fuels.reduce((function (a, b) {
                return a + b | 0;
              }), 0);
}

function calTotalfuel(fuels) {
  return $$Array.fold_left((function (a, b) {
                return a + b | 0;
              }), 0, fuels);
}

function getTotalFuel(input) {
  var strings = input.split("\n");
  return calTotalfuel(calculateFuel(strings.map(Caml_format.caml_int_of_string)));
}

var Part1 = {
  splitLines: splitLines,
  toIntegers: toIntegers,
  calculateFuel: calculateFuel,
  calculateTotalFuel: calculateTotalFuel,
  calTotalfuel: calTotalfuel,
  getTotalFuel: getTotalFuel
};

function getFuel(fuel) {
  if (fuel <= 0) {
    return 0;
  } else {
    return fuel + getFuel(getTotalFuel(String(fuel))) | 0;
  }
}

function main(input) {
  var strings = input.split("\n");
  var moduleFuels = calculateFuel(strings.map(Caml_format.caml_int_of_string));
  return calTotalfuel(moduleFuels.map(getFuel));
}

var Part2 = {
  getFuel: getFuel,
  main: main
};

var Day01 = {
  Part1: Part1,
  Part2: Part2
};

var file = Fs.readFileSync("./input.txt", "utf8");

getTotalFuel(file);

main(file);

exports.Day01 = Day01;
exports.file = file;
/* file Not a pure module */
