// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Part1$Day01 = require("./part1.bs.js");

function getFuel(fuel) {
  if (fuel <= 0) {
    return 0;
  } else {
    return fuel + getFuel(Part1$Day01.getTotalFuel(String(fuel))) | 0;
  }
}

function main(input) {
  var moduleFuels = Part1$Day01.calculateFuel(Part1$Day01.toIntegers(Part1$Day01.splitLines(input)));
  return Part1$Day01.calTotalfuel(moduleFuels.map(getFuel));
}

var Part2 = {
  getFuel: getFuel,
  main: main
};

var file = Fs.readFileSync("./input.txt", "utf8");

console.log(main(file));

exports.Part2 = Part2;
exports.file = file;
/* file Not a pure module */
