// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function splitLines(lines) {
  return lines.split("\n");
}

function toIntegers(strings) {
  return strings.map(Caml_format.caml_int_of_string);
}

function calculateFuel(masses) {
  return masses.map((function (mass) {
                return Js_math.floor(mass / 3 | 0) - 2 | 0;
              }));
}

function calculateTotalFuel(fuels) {
  return fuels.reduce((function (a, b) {
                return a + b | 0;
              }), 0);
}

function calTotalfuel(fuels) {
  return $$Array.fold_left((function (a, b) {
                return a + b | 0;
              }), 0, fuels);
}

function getTotalFuel(input) {
  var strings = input.split("\n");
  return calTotalfuel(calculateFuel(strings.map(Caml_format.caml_int_of_string)));
}

var file = Fs.readFileSync("./input.txt", "utf8");

getTotalFuel(file);

exports.splitLines = splitLines;
exports.toIntegers = toIntegers;
exports.calculateFuel = calculateFuel;
exports.calculateTotalFuel = calculateTotalFuel;
exports.calTotalfuel = calTotalfuel;
exports.getTotalFuel = getTotalFuel;
exports.file = file;
/* file Not a pure module */
